name: "Setup JS"

runs:
  using: "composite"

  steps:
    - name: Install Node.js
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
      with:
        node-version-file: "./.nvmrc"
        registry-url: "https://registry.npmjs.org"

    - name: Activate pnpm
      run: corepack enable
      shell: bash

    - name: Get pnpm store directory (for caching)
      id: pnpm-cache-dir
      run: |
        echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache pnpm store
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Check lockfile integrity
      run: pnpm install -r --lockfile-only --strict-peer-dependencies
      shell: bash

    - name: Install dependencies
      run: pnpm install -r --frozen-lockfile --strict-peer-dependencies
      shell: bash

    - name: Ensure dependency versions are consistent
      run: pnpm run consistent-versions
      shell: bash

    - name: Compile
      run: pnpm run build
      shell: bash
