name: build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup JS
        uses: ./.github/actions/js-setup

      - name: Test
        run: pnpm run test-all

      - name: Typecheck
        run: pnpm run typecheck-all

      - name: Lint
        run: pnpm run lint-all:ci

      - name: Prettier
        run: pnpm run prettier:check

      - name: Check Git
        uses: ./.github/actions/git-check
