name: release

on:
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup JS
        uses: ./.github/actions/js-setup

      - name: Clean build
        run: pnpm run reset-all

      - name: Release
        run: pnpm publish -r
        env:
          NPM_CONFIG_PROVENANCE: "true"
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check Git
        uses: ./.github/actions/git-check
