name: release

on:
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      actions: write
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Wipe cache
        uses: ./.github/actions/wipe-cache
        with:
          github_token: ${{ secrets.github_token }}

      - name: Setup JS
        uses: ./.github/actions/js-setup

      - name: Clean build
        run: pnpm run reset-all

      - name: Release
        run: pnpm publish -r
        env:
          NPM_CONFIG_PROVENANCE: "true"
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check Git
        uses: ./.github/actions/git-check
